import random

# Lists of words
def random_English_word():
    words = [
        "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
        "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
        "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
        "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Congo Democratic Republic",
        "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
        "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini Swaziland", "Ethiopia", "Fiji", "Finland",
        "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
        "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq",
        "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait",
        "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
        "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
        "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar Burma", "Namibia", "Nauru",
        "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman",
        "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar",
        "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia",
        "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan",
        "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
        "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City",
        "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe",
        
        # Fruits
        "apple", "banana", "orange", "grape", "strawberry",
        "blueberry", "raspberry", "blackberry", "watermelon", "melon",
        "pear", "peach", "plum", "apricot", "nectarine",
        "cherry", "kiwi", "pineapple", "mango", "pomegranate",
        "lemon", "lime", "grapefruit", "tangerine", "clementine",
        "mandarin", "kumquat", "yuzu", "pomelo", "ugli fruit",
        "dragonfruit", "passionfruit", "guava", "lychee", "rambutan",
        "longan", "mangosteen", "durian", "jackfruit", "papaya",
        "gooseberry", "elderberry", "boysenberry", "loganberry", "mulberry",
        "cranberry", "currant", "huckleberry", "cloudberry", "lingonberry",
        "avocado", "olive", "date", "fig", "persimmon",
        "loquat", "sapodilla",
        
        # Colours
        "red", "blue", "green", "yellow", "orange",
        "purple", "pink", "brown", "black", "white",
        "gray", "silver", "gold", "beige", "cyan",
        "crimson", "maroon", "scarlet", "ruby", "rose",
        "magenta", "fuchsia", "coral", "navy", "teal", 
        "turquoise", "aqua", "sky blue", "jade", "mint",
        "violet", "indigo", "amethyst", "amber", "goldenrod", 
        "chartreuse", "ivory", "charcoal", "burgundy", "mauve",
        "periwinkle", "vermilion", "cerulean", "taupe", "ochre",
        
        # Foods
        "steak", "chicken", "bacon", "pork chops", "sausage",
        "ham", "turkey", "duck", "lamb", "veal",
        "salmon", "tuna", "cod", "shrimp", "lobster",
        "crab", "scallops", "mussels", "oysters", "squid",
        "tofu", "tempeh", "seitan", "eggs", "quail eggs",
        "milk", "cheese", "cheddar", "mozzarella", "parmesan",
        "brie", "yogurt", "butter", "cream", "sour cream",
        "ice cream", "gelato", "custard", "pudding", "whipped cream",
        "cottage cheese", "cream cheese", "feta", "goat cheese", "provolone",
        "bread", "baguette", "sourdough", "naan", "pita",
        "tortilla", "croissant", "bagel", "muffin", "cornbread",
        "rice", "brown rice", "quinoa", "couscous", "barley",
        "oats", "granola", "cereal", "pasta", "spaghetti",
        "macaroni", "lasagna", "ramen", "udon", "soba",
        "broccoli", "carrot", "spinach", "kale", "lettuce",
        "cabbage", "cauliflower", "brussels sprouts", "asparagus", "green beans",
        "peas", "corn", "potato", "sweet potato", "yam",
        "onion", "garlic", "mushroom", "zucchini", "eggplant",
        "celery", "cucumber", "bell pepper", "radish", "beet",
        "chips", "popcorn", "pretzels", "crackers", "trail mix",
        "granola bar", "protein bar", "jerky", "peanut butter", "jam",
        "honey", "chocolate", "candy", "gummies", "licorice",
        "marshmallows", "donut", "cookie", "brownie", "cake",
        "pie", "cupcake", "cheesecake", "tiramisu", "macaron",
        "chicken soup", "tomato soup", "minestrone", "clam chowder", "miso soup",
        "pho", "gumbo", "chili", "lentil soup", "split pea soup",
        "matzo ball soup", "wonton soup", "borscht", "consomme",
        "ketchup", "mustard", "mayonnaise", "ranch", "bbq sauce",
        "hot sauce", "soy sauce", "teriyaki sauce", "hoisin sauce", "fish sauce",
        "pesto", "alfredo sauce", "marinara", "gravy", "hollandaise",
        "tahini", "sriracha", "wasabi", "hummus", "guacamole",
        "pancakes", "waffles", "french toast", "omelette", "scrambled eggs",
        "hash browns", "biscuits", "oatmeal", "grits",
        "yogurt parfait", "breakfast burrito", "english muffin",
        "pizza", "burger", "hotdog", "sandwich", "burrito",
        "taco", "sushi", "sashimi", "ravioli", "fried rice",
        "risotto", "noodles", "dumplings", "gyoza", "spring rolls",
        "samosa", "empanada", "curry", "tikka masala", "butter chicken",
        "biryani", "jollof rice",

        # Nature & Weather
        "forest", "river", "mountain", "ocean", "desert", 
        "valley", "thunder", "lightning", "breeze", "sunset",
        "sunrise", "rainbow", "hurricane", "tornado", "earthquake",
        "volcano", "tsunami", "avalanche", "blizzard", "drought",
        "flood", "wildfire", "tropical storm", "monsoon", "heatwave",
        "snowstorm", "hailstorm", "sandstorm", "dust storm", "fog",
        "mist", "smog", "pollution", "climate", "weather",
        "season", "spring", "summer", "fall", "autumn",
        "winter", "day", "night", "morning", "afternoon",
        "evening", "midnight", "noon", "dawn", "dusk",
        "cloud", "sky", "star", "moon", "sun",
        "planet", "earth", "galaxy", "universe", "cosmos",
        "constellation", "comet", "asteroid", "meteor", "meteorite",
        "rain", "snow", "sleet", "hail", "ice",
        "frost", "dew", "fog", "mist", "cloud",
        "thunderstorm", "lightning", "rainbow", "wind", "breeze",
        "gale", "hurricane", "tornado", "cyclone", "typhoon",

        # Actions & Verbs
        "run", "jump", "swim", "climb", "dance",
        "sing", "laugh", "cry", "think", "write",
        
        # Household Objects
        "chair", "table", "lamp", "mirror", "blanket",
        "pillow", "broom", "clock", "vase", "window",
        
        # Technology
        "computer", "keyboard", "mouse", "screen", "phone",
        "camera", "router", "battery", "charger", "software",
        
        # Clothing
        "shirt", "pants", "dress", "jacket", "socks",
        "shoes", "hat", "gloves", "scarf", "jeans",

        # Professions
        "doctor", "teacher", "engineer", "artist", "chef",
        "pilot", "writer", "scientist", "farmer", "driver",
        
        # Transportation
        "car", "bike", "bus", "train", "plane",
        "ship", "truck", "motorcycle", "scooter", "subway"

        # Positive Traits (150)
        "happy", "joyful", "cheerful", "optimistic", "lively", 
        "vibrant", "enthusiastic", "passionate", "energetic", "dynamic",
        "confident", "bold", "courageous", "fearless", "brave",
        "strong", "resilient", "determined", "persistent", "tenacious",
        "intelligent", "wise", "brilliant", "clever", "sharp",
        "creative", "imaginative", "innovative", "artistic", "talented",
        "kind", "compassionate", "empathetic", "gentle", "caring",
        "generous", "giving", "selfless", "thoughtful", "considerate",
        "honest", "trustworthy", "sincere", "genuine", "authentic",
        "loyal", "devoted", "faithful", "reliable", "dependable",
        "polite", "courteous", "respectful", "gracious", "well-mannered",
        "humorous", "witty", "funny", "playful", "lighthearted",
        "calm", "peaceful", "serene", "relaxed", "tranquil",
        "patient", "tolerant", "understanding", "forgiving", "accepting",
        "romantic", "affectionate", "loving", "tender", "warm",
        "elegant", "graceful", "sophisticated", "refined", "classy",
        "charming", "charismatic", "captivating", "engaging", "alluring",
        "adventurous", "daring", "bold", "spirited", "free-spirited",
        "ambitious", "driven", "motivated", "goal-oriented", "focused",
        "organized", "methodical", "systematic", "efficient", "productive",
        "flexible", "adaptable", "versatile", "open-minded", "receptive",
        "grateful", "appreciative", "thankful", "content", "satisfied",
        "humble", "modest", "unassuming", "down-to-earth", "approachable",
        "optimistic", "hopeful", "positive", "upbeat", "encouraging",
        "radiant", "glowing", "bright", "shining", "sparkling",
        "wholesome", "pure", "innocent", "virtuous", "noble",

        # Negative Traits (150)
        "sad", "depressed", "miserable", "gloomy", "melancholy",
        "angry", "furious", "enraged", "irritated", "annoyed",
        "anxious", "nervous", "worried", "stressed", "tense",
        "afraid", "scared", "fearful", "terrified", "panicked",
        "jealous", "envious", "resentful", "bitter", "spiteful",
        "guilty", "ashamed", "remorseful", "regretful", "contrite",
        "lonely", "isolated", "abandoned", "neglected", "forlorn",
        "bored", "uninterested", "apathetic", "indifferent", "disengaged",
        "tired", "exhausted", "weary", "fatigued", "drained",
        "lazy", "slothful", "idle", "unmotivated", "lethargic",
        "selfish", "greedy", "possessive", "hoarding", "stingy",
        "arrogant", "conceited", "vain", "egotistical", "narcissistic",
        "rude", "impolite", "disrespectful", "insolent", "discourteous",
        "dishonest", "deceitful", "lying", "manipulative", "sneaky",
        "cruel", "mean", "hurtful", "malicious", "vindictive",
        "stubborn", "obstinate", "inflexible", "rigid", "unyielding",
        "childish", "immature", "petty", "silly", "foolish",
        "clumsy", "awkward", "graceless", "uncoordinated", "bumbling",
        "messy", "disorganized", "sloppy", "untidy", "chaotic",
        "forgetful", "absent-minded", "scatterbrained", "careless", "negligent",
        "pessimistic", "cynical", "doubtful", "hopeless", "defeatist",
        "weak", "fragile", "feeble", "powerless", "helpless",
        "shy", "timid", "bashful", "reserved", "withdrawn",
        "clingy", "needy", "dependent", "desperate", "smothering",

        # Appearance (150)
        "beautiful", "pretty", "handsome", "gorgeous", "stunning",
        "attractive", "lovely", "cute", "adorable", "charming",
        "elegant", "graceful", "refined", "sophisticated", "classy",
        "glamorous", "stylish", "fashionable", "trendy", "chic",
        "fit", "toned", "athletic", "muscular", "slender",
        "slim", "lean", "skinny", "petite", "willowy",
        "plump", "chubby", "curvy", "voluptuous", "full-figured",
        "tall", "short", "average-height", "lanky", "stubby",
        "young", "youthful", "old", "elderly", "aged",
        "bald", "hairy", "shaggy", "bearded", "clean-shaven",
        "blonde", "brunette", "redhead", "auburn", "raven-haired",
        "pale", "fair", "rosy", "ruddy", "tanned",
        "dark-skinned", "olive-skinned", "porcelain", "freckled", "sun-kissed",
        "blue-eyed", "brown-eyed", "green-eyed", "hazel-eyed", "piercing-eyed",
        "round-faced", "oval-faced", "square-faced", "heart-faced", "angular-faced",
        "wrinkled", "smooth", "lined", "youthful", "weathered",
        "glowing", "radiant", "dull", "pale", "flushed",
        "scarred", "blemished", "clear-skinned", "acne-prone", "porous",
        "tattooed", "pierced", "makeup-free", "made-up", "natural",
        "well-groomed", "unkempt", "disheveled", "tousled", "bedraggled",
        "sparkling", "shiny", "glossy", "matte", "oily",
        "musky", "fragrant", "scented", "stinky", "odorless",
        "clean", "dirty", "filthy", "spotless", "immaculate",

        # Size & Shape (100)
        "big", "large", "huge", "enormous", "gigantic",
        "small", "tiny", "miniature", "minuscule", "microscopic",
        "long", "lengthy", "extended", "elongated", "stretched",
        "short", "brief", "compact", "stubby", "squat",
        "wide", "broad", "expansive", "spacious", "roomy",
        "narrow", "slim", "thin", "slender", "tight",
        "tall", "towering", "lofty", "elevated", "sky-high",
        "short", "low", "stunted", "dwarfed", "ground-level",
        "deep", "profound", "bottomless", "cavernous", "yawning",
        "shallow", "superficial", "surface-level", "slight", "insignificant",
        "heavy", "weighty", "massive", "bulky", "hefty",
        "light", "weightless", "airy", "feathery", "ethereal",
        "thick", "dense", "solid", "chunky", "substantial",
        "thin", "fine", "delicate", "wispy", "gossamer",
        "round", "circular", "spherical", "globular", "orb-shaped",
        "square", "rectangular", "boxy", "angular", "geometric",
        "pointy", "sharp", "jagged", "spiky", "prickly",
        "soft", "squishy", "malleable", "pliable", "yielding",
        "hard", "firm", "rigid", "stiff", "unyielding",

        # Texture & Feel (100)
        "smooth", "silky", "sleek", "glossy", "polished",
        "rough", "coarse", "bumpy", "uneven", "textured",
        "furry", "fuzzy", "hairy", "shaggy", "bristly",
        "slick", "slippery", "greasy", "oily", "lubricated",
        "sticky", "tacky", "gummy", "adhesive", "clingy",
        "dry", "arid", "parched", "dehydrated", "thirsty",
        "wet", "damp", "moist", "soggy", "waterlogged",
        "fluffy", "airy", "light", "downy", "cloud-like",
        "dense", "compact", "solid", "thick", "impenetrable",
        "crunchy", "crispy", "brittle", "crumbly", "snappy",
        "chewy", "rubbery", "tough", "leathery", "resilient",
        "gooey", "sticky", "viscous", "gelatinous", "syrupy",
        "powdery", "dusty", "chalky", "granular", "gritty",
        "velvety", "plush", "cushioned", "soft", "luxurious",
        "prickly", "thorny", "barbed", "spiny", "irritating",
        "metallic", "shiny", "reflective", "cold", "hard",
        "woody", "earthy", "organic", "natural", "rough-hewn",
        "glassy", "transparent", "clear", "crystalline", "see-through",
        "mossy", "fuzzy", "overgrown", "dank", "humid",

        # Temperature (50)
        "hot", "scalding", "boiling", "blazing", "fiery",
        "warm", "toasty", "temperate", "lukewarm", "tepid",
        "cold", "freezing", "frigid", "icy", "chilly",
        "cool", "refreshing", "brisk", "crisp", "nippy",
        "humid", "muggy", "sticky", "sultry", "steamy",
        "dry", "arid", "parched", "dehydrated", "thirsty",
        "frozen", "frosty", "glacial", "polar", "subzero",
        "melting", "thawing", "defrosting", "warming", "heating",
        "burning", "smoldering", "scorching", "sweltering", "roasting",
        "shivering", "quivering", "trembling", "chattering", "numb",

        # Age & Condition (50)
        "new", "fresh", "modern", "current", "recent",
        "old", "ancient", "aged", "vintage", "antique",
        "young", "youthful", "immature", "teenage", "childlike",
        "mature", "grown", "developed", "seasoned", "experienced",
        "decaying", "rotting", "decomposing", "spoiled", "rancid",
        "pristine", "untouched", "unspoiled", "perfect", "flawless",
        "worn", "faded", "weathered", "tattered", "threadbare",
        "polished", "refurbished", "renewed", "restored", "revitalized",
        "broken", "shattered", "fractured", "cracked", "damaged",
        "repaired", "fixed", "mended", "patched", "healed"
    ]
    return random.choice(words)